apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiny-web-client-ingress
  namespace: tiny-web-client
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "tiny-wc.2beens.xyz"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tiny-web-client-clusterip-service
            port:
              number: 80
