apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.image.healthPort }}
          initialDelaySeconds: 10
          periodSeconds: 60
        env:
        - name: TINY_API_HOST
          value: {{ .Values.configmap.apihost | quote }}
        - name: TINY_API_INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
# make the tiny api accessible from the outside
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
