# TODO: add ingress for mongodb express
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-service-mongodb-express
  namespace: tiny-service-mongodb
  labels:
    app: tiny-service-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-service-mongodb
  template:
    metadata:
      namespace: tiny-service-mongodb
      labels:
        app: tiny-service-mongodb
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: tiny-service-mongodb-configmap
              key: dbUsername
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            configMapKeyRef:
              name: tiny-service-mongodb-configmap
              key: dbPassword
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: tiny-service-mongodb-configmap
              key: databaseUrl
