apiVersion: v1
kind: ConfigMap
metadata:
  name: tiny-service-configmap
  namespace: tiny-service
data:
  serviceHost: "0.0.0.0"
  # servicename.namespace.svc.cluster.local
  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
  mongoHost: tiny-service-mongodb-service.tiny-service-mongodb.svc.cluster.local
