apiVersion: v1
kind: Service
metadata:
  name: tiny-service-clusterip-service
  namespace: tiny-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9002
  selector:
    app: tiny-service
