appName: tiny-api
replicaCount: 5
revisionHistoryLimit: 4

deployment:
  name: tiny-api-deployment

image:
  name: tiny-api
  repository: stubin87/tiny-api
  pullPolicy: IfNotPresent
  tag: v1.1.0
  containerPort: 9001
  healthPort: 9001

service:
  name: tiny-api-service
  type: LoadBalancer
  port: 9001
  targetPort: 9001
  nodePort: 30000

configmap:
  apihost: 0.0.0.0
