apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-api-deployment
  namespace: tiny-api
  labels:
    app: tiny-api
spec:
  replicas: 5
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: tiny-api
  template:
    metadata:
      namespace: tiny-api
      labels:
        app: tiny-api
    spec:
      containers:
        - name: tiny-api
          image: stubin87/tiny-api:v1.4.0
          ports:
            - containerPort: 9001
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 60
          env:
            - name: TINY_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: tiny-api-configmap
                  key: apihost
            - name: TINY_API_TSE_HOST
              valueFrom:
                configMapKeyRef:
                  name: tiny-api-configmap
                  key: tsehost
            - name: TINY_API_INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
