apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiny-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "tiny.api.lb.2beens.xyz"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tiny-api-clusterip-service
            port:
              number: 80
